# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install uv (https://docs.astral.sh/uv/)
      - pip install uv
    post_install:
      # Install dependencies into the RTD virtualenv using uv
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --frozen
    # Replace the 'mkdocs' key with a manual 'build' job
    build:
      html:
        # Create the directory first to prevent errors
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        # Build directly into the RTD output directory
        - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv run mkdocs build --config-file mkdocs.yml --site-dir $READTHEDOCS_OUTPUT/html/

mkdocs:
  configuration: mkdocs.yml
